### ISSUE TITLE
タブバー画面を作成する

### ISSUE THREAD

**Issue by king-kazu39** [AyanoHara/SamplePhoneBook#1]
デザイン↓
![スクリーンショット 2021-01-14 20 34 12](https://user-images.githubusercontent.com/25321380/104585775-e6677880-56a7-11eb-8e21-a3796c8e7846.png)

- [x] 上記のようなタブバーを作成してください（ViewにはわかりやすくText（"プロフィール一覧"）とおいてください）
- [x] アイコンはSF Symbolから選択してきてください
- [x] 出来上がったタブバー画面はSceneデリゲートのrootViewに指定してアプリ起動時に開けるようにしましょう
- [x] ここまでできたらプルリクをおくってね

コミットメッセージは下記のようにして下さい。
```
$git add .
$git commit -m "fix #1 タブバー画面作成"  // #1はissue番号です。issue番号はissueタイトルの添字です。
```

コミットは小まめにやった方がいいよ。
コミットをまとめるときは
```
$git rebase -i XXXXX   // XXXXはまとめる前のコミット番号
```

**Comment by AyanoHara** [comment]
@king-kazu39 
一応大体は完成したのですが、アイコンをNavigationBarのタイトルに追加出来ずに苦戦しています。

.navigationBarItems(leading: )このプロパティを使用してアイコンをNavigationBarの左側に置くことは出来たのですが、タイトルのすぐ左に追加する方法が調べてもわかりませんでした💧

あと、プロフィール一覧のアイコンが同じものが見つからなかったので似ているものを使用しました。

お時間ある時に確認お願いします！

![プロフィール一覧_iPhone11](https://user-images.githubusercontent.com/65425673/104989668-47070480-5a5e-11eb-8edf-a5b2f0e1c27f.png)  ![プロフィール登録_iPhone11](https://user-images.githubusercontent.com/65425673/104989678-4b332200-5a5e-11eb-90f7-3e279be5bb5f.png)
